# Generated by Django 4.1.5 on 2023-08-23 12:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_academician1_alumni1_industry1'),
    ]

    operations = [
        migrations.AddField(
            model_name='industry1',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 8, 23, 12, 24, 54, 957544, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
